version: '2.3'

networks:
  default:
    name: solva-tech-network
    ipam:
      driver: default
      config:
        - subnet: 173.36.0.0/16

services:
  solva-tech-db:
    image: postgres:15
    container_name: solva-tech-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "solva"
      POSTGRES_DB: "postgres"
    ports:
      - "10010:5432"
    volumes:
      - ~/volumes/solva-tech/pg-data:/var/lib/postgresql/data
      - ./auth-init:/docker-entrypoint-initdb.d
    command:
      - "docker-entrypoint.sh"
      - "-c"
      - "max-connections=800"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  es:
    container_name: solva-tech-es
    image: elasticsearch:8.3.2
    # noinspection ComposeUnknownValues
    mem_limit: "${MYBPM_ES_MEMORY_MAIN:-3000M}"
    restart: always
    ports:
      - "9200:9200"
    # noinspection SpellCheckingInspection
    environment:
      #- cluster.name=docker-cluster
      - discovery.type=single-node
      - node.name=from-plugin
      - bootstrap.memory_lock=true
      - index.store.type=hybridfs
      - "ES_JAVA_OPTS=-Xms${MYBPM_ES_MEMORY_JAVA:-1500M} -Xmx${MYBPM_ES_MEMORY_JAVA:-1500M}"
      #      - TAKE_FILE_OWNERSHIP=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/volumes/solva-tech/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/volumes/solva-tech/elasticsearch/logs:/usr/share/elasticsearch/logs

  solva-tech-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - solva-tech-db
      - redis
      - es
    environment:
      DATABASE_HOST: solva-tech-db
      DATABASE_PORT: 5432
      DATABASE_USER: solva
      DATABASE_PASSWORD: 1234
      REDIS_HOST: redis
      REDIS_PORT: 6379
