spring:
  application:
    name: solva-tech-oraz

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:10010}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:solva}
    password: ${DATABASE_PASSWORD:1234}

  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: public

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  elasticsearch:
    port: ${ELASTIC_SEARCH_PORT:9200}
    host: ${ELASTIC_SEARCH_HOST:localhost}
    schema: ${ELASTIC_SEARCH_SCHEMA:http}

  twelve:
    api: "c86562cc65ad4e029dc46a40585de951"
